apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: production
data:
  HTTP_PROXY: 'http://squid.internal:3128/'
  HTTPS_PROXY: 'http://squid.internal:3128/'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: staging
data:
  HTTP_PROXY: 'http://squid.internal:3128/'
  HTTPS_PROXY: 'http://squid.internal:3128/'

---

apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: global-proxy-config
  namespace: production
spec:
  selector:
    matchLabels:
      useProxy: "true"
  envFrom:
    - configMapRef:
        name: proxy-config

---

apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: global-proxy-config
  namespace: staging
spec:
  selector:
    matchLabels:
      useProxy: "true"
  envFrom:
    - configMapRef:
        name: proxy-config
