---

kind: Service
apiVersion: v1
metadata:
  name: insights-ubuntu-com
spec:
  selector:
    app: insights.ubuntu.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: insights-ubuntu-com
  labels:
    useProxy: "true"
spec:
  replicas: 9
  template:
    metadata:
      labels:
        app: insights.ubuntu.com
        useProxy: "true"
    spec:
      containers:
        - name: insights-ubuntu-com
          image: prod-comms.docker-registry.canonical.com/insights.ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: proxy-config
                optional: true
          readinessProbe:
            httpGet:
              path: /status
              port: 80
            periodSeconds: 3
            successThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5

---
