---

kind: Service
apiVersion: v1
metadata:
  name: snapcraft-io
spec:
  selector:
    app: snapcraft.io
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: snapcraft-io
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: snapcraft.io
    spec:
      containers:
        - name: snapcraft-io
          image: ${IMAGE_TO_DEPLOY}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---
