---

kind: Service
apiVersion: v1
metadata:
  name: usn-ubuntu-com
spec:
  selector:
    app: usn.ubuntu.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: usn-ubuntu-com
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: usn.ubuntu.com
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: usn-ubuntu-com
          image: prod-comms.docker-registry.canonical.com/usn.ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ["/usr/sbin/nginx","-s","quit"]
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---
