---

kind: Service
apiVersion: v1
metadata:
  name: PROJECTNAME
spec:
  selector:
    app: PROJECTDOMAIN
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: PROJECTNAME
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: PROJECTDOMAIN
    spec:
      containers:
        - name: PROJECTNAME
          image: prod-comms.docker-registry.canonical.com/PROJECTDOMAIN:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 10
            initialDelaySeconds: 15
            periodSeconds: 15

---
