---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: threesixty-canonical-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: threesixty-canonical-com-tls
    hosts:
    - 360.canonical.com
  rules:
  - host: 360.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: threesixty-canonical-com
          servicePort: 80

---
