---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cloud-init-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: cloud-init-io-tls
    hosts:
    - cloud-init.io
  rules:
  - host: cloud-init.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud-init-io
          servicePort: 80

---
