---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cn-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'ubuntu-china.cn' ) {
        rewrite ^ https://cn.ubuntu.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: cn-ubuntu-com-tls
    hosts:
    - cn.ubuntu.com
  rules:
  - host: cn.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cn-ubuntu-com
          servicePort: 80
  - host: ubuntu-china.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: cn-ubuntu-com
          servicePort: 80
---
