---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cn-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: cn-ubuntu-com-tls
    hosts:
    - cn.ubuntu.com
  rules:
  - host: cn.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cn-ubuntu-com
          servicePort: 80

---
