---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: conjure-up-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.conjure-up.io' ) {
        rewrite ^ https://conjure-up.io$request_uri permanent;
      }
spec:
  tls:
  - secretName: conjure-up-io-tls
    hosts:
    - conjure-up.io
    - www.conjure-up.io
  rules:
  - host: conjure-up.io
    http:
      paths:
      - path: /
        backend:
          serviceName: conjure-up-io
          servicePort: 80
  - host: www.conjure-up.io
    http:
      paths:
      - path: /
        backend:
          serviceName: conjure-up-io
          servicePort: 80

---
