---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docs-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: docs-ubuntu-com-tls
    hosts:
    - docs.snapcraft.io
  rules:
  - host: docs.snapcraft.io
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-ubuntu-com
          servicePort: 80

---
