---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: insights-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet:
      rewrite ^ https://blog.ubuntu.com$request_uri? permanent;
spec:
  tls:
  - secretName: insights-ubuntu-com-tls
    hosts:
    - insights.ubuntu.com
  rules:
  - host: insights.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blog-ubuntu-com
          servicePort: 80

---
