---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: maas-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.maas.io' ) {
        rewrite ^ https://maas.io$request_uri permanent;
      }
spec:
  tls:
  - secretName: maas-io-tls
    hosts:
    - maas.io
    - www.maas.io
  rules:
  - host: maas.io
    http:
      paths:
      - path: /
        backend:
          serviceName: maas-io
          servicePort: 80
  - host: www.maas.io
    http:
      paths:
      - path: /
        backend:
          serviceName: maas-io
          servicePort: 80

---
