---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: netplan-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: netplan-io-tls
    hosts:
    - netplan.io
  rules:
  - host: netplan.io
    http:
      paths:
      - path: /
        backend:
          serviceName: netplan-io
          servicePort: 80

---
