---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: snapcraft-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - secretName: snapcraft-io-tls
    hosts:
    - snapcraft.io
  rules:
  - host: snapcraft.io
    http:
      paths:
      - path: /
        backend:
          serviceName: snapcraft-io
          servicePort: 80

---
