---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: snapcraft-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.snapcraft.io' ) {
        rewrite ^ https://snapcraft.io$request_uri permanent;
      }
spec:
  tls:
  - secretName: snapcraft-io-tls
    hosts:
    - snapcraft.io
    - www.snapcraft.io
  rules:
  - host: snapcraft.io
    http:
      paths:
      - backend:
          serviceName: snapcraft-io
          servicePort: 80
  - host: www.snapcraft.io
    http:
      paths:
      - backend:
          serviceName: snapcraft-io
          servicePort: 80

---
