---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cn-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      if ($host = 'staging.ubuntu-china.cn' ) {
        rewrite ^ https://cn.staging.ubuntu.com$request_uri? permanent;
      }

spec:
  tls:
  - secretName: cn-staging-ubuntu-com-tls
    hosts:
    - cn.staging.ubuntu.com
    - staging.ubuntu-china.cn
  rules:
  - host: cn.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cn-ubuntu-com
          servicePort: 80
  - host: staging.ubuntu-china.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: cn-ubuntu-com
          servicePort: 80

---
