---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: staging-canonical-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: staging-canonical-com-tls
    hosts:
    - staging.canonical.com
  rules:
  - host: staging.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: canonical-com
          servicePort: 80

---
