---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: www-staging-canonical-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      if ($host = 'staging.canonical.com' ) {
        rewrite ^ https://www.staging.canonical.com$request_uri permanent;
      }
spec:
  tls:
  - secretName: www-staging-canonical-com-tls
    hosts:
    - www.staging.canonical.com
    - staging.canonical.com
  rules:
  - host: www.staging.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: www-canonical-com
          servicePort: 80

---
